---
- name: Install nginx
  apt: 
    name: nginx
    force_apt_get: yes
    state: latest
    update_cache: yes
  when: ansible_host == groups.System_group.0

- name: Config nginx
  template: 
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  when: ansible_host == groups.System_group.0

- name: Reload it
  shell: |
    nginx -s reload
  when: ansible_host == groups.System_group.0

# -test mode-----------------------------------------------------------------------------------------------------------------------

# - name: Install nginx
#   apt: 
#     name: nginx
#     force_apt_get: yes
#     state: latest
#     update_cache: yes
#   when: ansible_host == groups.Back_end_group.0

# - name: Config nginx
#   template: 
#     src: nginx.conf.j2
#     dest: /etc/nginx/nginx.conf
#   when: ansible_host == groups.Back_end_group.0

# - name: Reload it
#   shell: |
#     nginx -s reload
#   when: ansible_host == groups.Back_end_group.0