---
- name: Send docker-compose file
  copy:
    src: ~/Desktop/ansible_deployment/dockerFileFolder/docker-compose.yml
    dest: ~/
  when: ansible_host == groups.System_group.0

- name: Execute production
  docker_stack:
    state: present
    name: Mission
    compose:
      - ~/docker-compose.yml
  when: ansible_host == groups.System_group.0
